apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-prometheus-stack-tritonmetrics
  namespace: monitoring
  labels:
      release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: triton-custom
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
  - port: metrics-triton
    interval: 10s
    path: /metrics 
