apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
  namespace: vss
# type: Opaque
data:
  mongo_username: cm9vdA==
  mongo_password: MTIzNDU2YUA=

  singlestore_username: cm9vdA==
  singlestore_password: MTIzNDU2YUFA

  redis_password: MTIzNDU2YUA=

  s3_access_key_id: YWRtaW4=
  s3_secret_access_key: MTIzNDU2YUA=


